//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakkesModInjectorCs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SAFE_MODE {
            get {
                return ((bool)(this["SAFE_MODE"]));
            }
            set {
                this["SAFE_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DISABLE_WARNINGS {
            get {
                return ((bool)(this["DISABLE_WARNINGS"]));
            }
            set {
                this["DISABLE_WARNINGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AUTO_UPDATE {
            get {
                return ((bool)(this["AUTO_UPDATE"]));
            }
            set {
                this["AUTO_UPDATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool STARTUP_MINIMIZE {
            get {
                return ((bool)(this["STARTUP_MINIMIZE"]));
            }
            set {
                this["STARTUP_MINIMIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MINIMIZE_HIDE {
            get {
                return ((bool)(this["MINIMIZE_HIDE"]));
            }
            set {
                this["MINIMIZE_HIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool STARTUP_RUN {
            get {
                return ((bool)(this["STARTUP_RUN"]));
            }
            set {
                this["STARTUP_RUN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TOPMOST {
            get {
                return ((bool)(this["TOPMOST"]));
            }
            set {
                this["TOPMOST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OFFLINE_MODE {
            get {
                return ((bool)(this["OFFLINE_MODE"]));
            }
            set {
                this["OFFLINE_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CHANGELOG_COLLAPSED {
            get {
                return ((bool)(this["CHANGELOG_COLLAPSED"]));
            }
            set {
                this["CHANGELOG_COLLAPSED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool JUST_UPDATED {
            get {
                return ((bool)(this["JUST_UPDATED"]));
            }
            set {
                this["JUST_UPDATED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public int TIMEOUT_VALUE {
            get {
                return ((int)(this["TIMEOUT_VALUE"]));
            }
            set {
                this["TIMEOUT_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("timeout")]
        public string INJECTION_TYPE {
            get {
                return ((string)(this["INJECTION_TYPE"]));
            }
            set {
                this["INJECTION_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string WIN64_FOLDER {
            get {
                return ((string)(this["WIN64_FOLDER"]));
            }
            set {
                this["WIN64_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BM_VERSION {
            get {
                return ((string)(this["BM_VERSION"]));
            }
            set {
                this["BM_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string RL_VERSION {
            get {
                return ((string)(this["RL_VERSION"]));
            }
            set {
                this["RL_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BakkesModInjectorCs - Community Edition")]
        public string WINDOW_TTILE {
            get {
                return ((string)(this["WINDOW_TTILE"]));
            }
            set {
                this["WINDOW_TTILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v2.0.8")]
        public string INJECTOR_VERSION {
            get {
                return ((string)(this["INJECTOR_VERSION"]));
            }
            set {
                this["INJECTOR_VERSION"] = value;
            }
        }
    }
}
